logo = true
logoText = "NUFE Wiki"
logoType = "short" # long, short
description = "The NUFE Unofficial Wiki site."
editBaseURL = "https://github.com/LokmenoWer/nufe-wiki/tree/main/content"
themeOptions = ["light", "dark"]
favicon = "./logo.png"
useFaviconGenerator = true # https://www.favicon-generator.org/

wideViewAsDefault = true

enableWideBlogSwitch = true
enableTocSwitch = true
enableLandingBackground = true
enableSearch = true
enableSearchHighlight = true
enableLangChange = false
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/LokmenoWer/nufe-wiki/"

enableComment = true
[utterances]       # https://utteranc.es/
  owner = "LokmenoWer"              # Your GitHub ID
  repo = "nufe-wiki-comment"               # The repo to store comments