name: 报告新的猫猫
description: 报告新的猫猫
labels: [CATS]
body:
  - type: markdown
    attributes:
      value: 感谢您的报告，请根据该表单填充必要信息。
  - type: input
    id: cat-name
    attributes:
      label: 猫猫的名字
      description: 请填写猫猫的名字
    validations:
      required: true
  - type: dropdown
    id: labels-jueyu
    attributes:
      label: 绝育状态
      multiple: false
      options:
        - 已经绝育
        - 未绝育
        - 尚不清楚
  - type: dropdown
    id: labels-lingyang
    attributes:
      label: 领养状态
      multiple: false
      options:
        - 已领养
        - 未领养
        - 尚不清楚
  - type: checkboxes
    id: license
    attributes:
      label: 以 CC-BY-SA 4.0 协议分发
      description: 本站采用 [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh-Hans) 协议分发内容
      options:
        - label: 我同意以 CC-BY-SA 4.0 协议分发
          required: true
    